In [1]:
from keras.models import load_model
import numpy as np

Using TensorFlow backend.


In [2]:

model = load_model('ECG.h5')
model.compile(loss='categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])

from skimage.transform import resize

def detect(frame):
    try:
        beat_type=['Fusion beat','Normal beat','Supraventricular ectopic beat','unknown beat','Ventricular ectopic beat']
        img = resize(frame,(64,64))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(beat_type[prediction[0]])
    except AttributeError:
        print("shape not found")


In [3]:
import cv2

In [4]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Ventricular_ectopic_beat\Efig_63.png'
detect(cv2.imread(path))

[[1.1780900e-01 1.4500200e-05 1.7881623e-03 2.1343496e-01 6.6695333e-01]]
Ventricular ectopic beat


In [5]:
detect(cv2.imread("Afig_36.png"))

[[0.31072676 0.19077691 0.39394188 0.10311592 0.00143858]]
Supraventricular ectopic beat


In [6]:
detect(cv2.imread("300px-PVC10.jpg"))

[[1.03322367e-04 3.95871939e-06 9.97803748e-01 2.08890578e-03
  1.13980006e-10]]
Supraventricular ectopic beat


In [7]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Fusion_beat\Ffig_675.png'
detect(cv2.imread(path))

[[7.5540286e-01 1.1877745e-05 9.6374892e-02 7.9098260e-03 1.4030062e-01]]
Fusion beat


In [8]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Fusion_beat\Ffig_727.png'
detect(cv2.imread(path))

[[9.6681422e-01 1.3865161e-04 1.0451042e-02 2.2279795e-03 2.0368138e-02]]
Fusion beat


In [9]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Fusion_beat\Ffig_780.png'
detect(cv2.imread(path))

[[8.5092807e-01 2.6672278e-04 1.0965350e-02 8.3724089e-02 5.4115850e-02]]
Fusion beat


In [10]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Normal_beat\fig_72553.png'
detect(cv2.imread(path))

[[2.2740558e-01 7.5801647e-01 1.0474103e-02 3.7921555e-03 3.1166198e-04]]
Normal beat


In [11]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Normal_beat\fig_72578.png'
detect(cv2.imread(path))

[[8.3030927e-01 9.0182265e-03 7.1890466e-02 8.8744693e-02 3.7323600e-05]]
Fusion beat


In [12]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Normal_beat\fig_72508.png'
detect(cv2.imread(path))

[[2.1171920e-01 4.2087107e-04 5.9695777e-02 7.2815186e-01 1.2301514e-05]]
unknown beat


In [13]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Supraventricular_ectopic_beat\Afig_2348.png'
detect(cv2.imread(path))

[[0.39773312 0.00318633 0.5867468  0.01098223 0.00135154]]
Supraventricular ectopic beat


In [14]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Supraventricular_ectopic_beat\Afig_2242.png'
detect(cv2.imread(path))

[[0.04875065 0.00213413 0.7592662  0.00928328 0.18056573]]
Supraventricular ectopic beat


In [15]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Supraventricular_ectopic_beat\Afig_2358.png'
detect(cv2.imread(path))

[[1.6076000e-01 1.3380585e-02 8.1858653e-01 6.0166884e-04 6.6711409e-03]]
Supraventricular ectopic beat


In [16]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Supraventricular_ectopic_beat\Afig_2307.png'
detect(cv2.imread(path))

[[0.3755698  0.01131522 0.5900268  0.00410575 0.01898242]]
Supraventricular ectopic beat


In [17]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Unknown_beat\pfig_31203969.png'
detect(cv2.imread(path))

[[9.9829668e-01 8.8875513e-06 7.5860874e-04 3.3122330e-04 6.0449389e-04]]
Fusion beat


In [18]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Ventricular_ectopic_beat\Efig_60.png'
detect(cv2.imread(path))

[[5.4330733e-02 6.2337626e-06 1.6919837e-03 5.0671947e-01 4.3725160e-01]]
unknown beat


In [19]:
path=r'C:\Users\venkat sai\Desktop\InternshipProject\ECG arrhythmia images\Test_dataset\Ventricular_ectopic_beat\Efig_63.png'
detect(cv2.imread(path))

[[1.1780900e-01 1.4500200e-05 1.7881623e-03 2.1343496e-01 6.6695333e-01]]
Ventricular ectopic beat
